# Generated by Django 5.2.4 on 2025-07-17 11:55

from django.db import migrations


def create_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Instructor')
    Group.objects.get_or_create(name='Student')


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
